name: Build and Publish STBootLib

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        type: choice
        options:
          - pre-release
          - final
        default: pre-release

  push:
    branches:
      - '!master'
 
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'STBootLib.sln'
      MAJOR: '0'
      MINOR: '2'
      PATCH: '0'
           
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Sets env vars for final
      if: ${{ inputs.release-type == 'final'}}
      run: |
        echo "VERSIONSUFFIX=''" >> $GITHUB_ENV
        git tag "$MAJOR.$MINOR.$PATCH-${{github.run_attempt}}"
        git push origin ${{github.run_id}}

    - name: Sets env vars for pre-release
      if: ${{ inputs.release-type == 'pre-release'}} 
      run: echo "VERSIONSUFFIX=pre-${{github.run_attempt}}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:VersionPrefix="$MAJOR.$MINOR.$PATCH" -p:VersionSuffix="$VERSIONSUFFIX" --no-restore

    # No test available yet
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_APIKEY}} -SkipDuplicate



